"use client";
import { useEffect, useState } from "react";
import type { FinanceIntegrityVerificationDTO } from "@/lib/integrity/types";
export function FinanceIntegrityVerification({ code }: { code: string }) {
  const [proof, setProof] = useState<FinanceIntegrityVerificationDTO | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void (async () => { try { const response = await fetch(`/api/v2/finance-integrity/verify/${encodeURIComponent(code)}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Verification failed"); setProof(payload.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Verification failed"); } })(); }, [code]);
  if (error) return <div className="rounded-lg border border-amber-200 bg-amber-50 p-5 text-amber-900"><h1 className="text-xl font-semibold">Proof unavailable</h1><p className="mt-2 text-sm">{error}</p></div>;
  if (!proof) return <p className="text-sm text-slate-600">Checking proof…</p>;
  return <div className="space-y-5 rounded-xl border bg-white p-6 shadow-sm"><header><h1 className="text-2xl font-semibold">AGAPE financial record verification</h1><p className="mt-1 text-sm text-slate-600">This page verifies a cryptographic commitment. It does not disclose the financial document or process a payment.</p></header><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Record</dt><dd>{proof.sourceType === "finance_cleared_budget" ? "Finance-cleared budget" : "Finance-verified liquidation"} revision {proof.sourceVersion}</dd></div><div><dt className="text-slate-500">Anchor status</dt><dd>{proof.anchorStatus.replaceAll("_", " ")}</dd></div><div><dt className="text-slate-500">Source validity</dt><dd>{proof.sourceValidity}</dd></div><div><dt className="text-slate-500">Network</dt><dd>{proof.networkKey ?? "Not anchored"}</dd></div><div className="sm:col-span-2"><dt className="text-slate-500">SHA-256 commitment</dt><dd className="break-all font-mono text-xs">{proof.canonicalHash}</dd></div>{proof.transactionHash && <div className="sm:col-span-2"><dt className="text-slate-500">Transaction hash</dt><dd className="break-all font-mono text-xs">{proof.transactionHash}</dd></div>}</dl>{proof.sourceValidity !== "active" && <p className="rounded-md bg-amber-50 p-3 text-sm text-amber-900">This proof remains valid for the historical version, but AGAPE marks the source as {proof.sourceValidity}.</p>}</div>;
}
