"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import type { FinanceIntegrityRuntimeDTO } from "@/lib/integrity/types";
import { Phase2Notice, StatusPill, inputClass, primaryButton } from "@/components/phase2/Phase2Ui";

const ids = (value: FormDataEntryValue | null) => String(value ?? "").split(/[\s,]+/).map((item) => item.trim()).filter(Boolean);

export function FinanceIntegrityRuntimeManager() {
  const [runtime, setRuntime] = useState<FinanceIntegrityRuntimeDTO | null>(null);
  const [message, setMessage] = useState<{ text: string; tone: "info" | "error" | "success" } | null>(null);
  const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/v2/finance-integrity/runtime", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to load runtime"); setRuntime(payload.data); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load runtime", tone: "error" }); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(null); const form = new FormData(event.currentTarget);
    try { const response = await fetch("/api/v2/finance-integrity/runtime", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode: form.get("mode"), providerKey: form.get("providerKey"), networkKey: form.get("networkKey") || null, contractReference: form.get("contractReference") || null, syntheticUserIds: ids(form.get("syntheticUserIds")), syntheticSourceIds: ids(form.get("syntheticSourceIds")) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Unable to save runtime"); setMessage({ text: "Runtime updated. Provider secrets remain in the deployment secret store.", tone: "success" }); await load(); }
    catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to save runtime", tone: "error" }); } finally { setBusy(false); }
  }
  return <div className="space-y-5"><header><h1 className="text-2xl font-semibold">Financial integrity configuration</h1><p className="mt-1 text-sm text-slate-600">Technical configuration only. Admin cannot read budgets, liquidations, receipts, or financial documents here.</p></header>{message && <Phase2Notice message={message.text} tone={message.tone} />}<div className="rounded-xl border bg-white p-5 shadow-sm"><div className="grid gap-3 text-sm sm:grid-cols-3"><div>Server gate <StatusPill value={runtime?.serverEnabled ? "enabled" : "off"} /></div><div>Database mode <StatusPill value={runtime?.mode ?? "unavailable"} /></div><div>Provider <StatusPill value={runtime?.providerKey ?? "unconfigured"} /></div></div></div><form onSubmit={save} className="grid gap-4 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-2"><label className="text-sm">Mode<select className={`${inputClass} mt-1`} name="mode" defaultValue={runtime?.mode ?? "off"}><option value="off">Off</option><option value="synthetic">Synthetic</option><option value="live">Live (requires reviewed provider)</option></select></label><label className="text-sm">Provider key<input className={`${inputClass} mt-1`} name="providerKey" defaultValue={runtime?.providerKey ?? "unconfigured"} pattern="[a-z][a-z0-9_-]{0,63}" required /></label><label className="text-sm">Network key<input className={`${inputClass} mt-1`} name="networkKey" defaultValue={runtime?.networkKey ?? ""} /></label><label className="text-sm">Contract reference<input className={`${inputClass} mt-1`} name="contractReference" defaultValue={runtime?.contractReference ?? ""} /></label><label className="text-sm md:col-span-2">Synthetic actor UUIDs<textarea className="mt-1 min-h-20 w-full rounded-md border p-2 font-mono text-xs" name="syntheticUserIds" /></label><label className="text-sm md:col-span-2">Synthetic proposal/program UUIDs<textarea className="mt-1 min-h-20 w-full rounded-md border p-2 font-mono text-xs" name="syntheticSourceIds" /></label><p className="text-xs text-slate-600 md:col-span-2">Only canonical hashes and minimal proof metadata leave AGAPE. This feature does not process funds or store files on-chain.</p><button className={`${primaryButton} md:col-span-2`} disabled={busy}>{busy ? "Saving…" : "Save runtime configuration"}</button></form></div>;
}
