"use client";

import { useEffect } from "react";
import { Printer, ArrowLeft } from "lucide-react";
import Link from "next/link";

// Renders an AI report in a print-friendly layout and auto-fires the browser
// print dialog. The print stylesheet in globals.css hides the dashboard
// chrome; this page additionally drops the .print-hidden helpers from view.

interface Report {
  id:            string;
  title:         string;
  period_start:  string;
  period_end:    string;
  narrative:     string;
  status:        string;
  created_at:    string;
}

const fmtDate = (d: string) =>
  new Date(d).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

export default function PrintReportClient({
  report,
  generatedBy,
}: {
  report:      Report;
  generatedBy: string | null;
}) {
  useEffect(() => {
    // Small delay so layout settles before the print dialog opens; otherwise
    // some browsers capture the page mid-paint.
    const t = window.setTimeout(() => window.print(), 250);
    return () => window.clearTimeout(t);
  }, []);

  return (
    <div className="max-w-3xl mx-auto bg-card text-foreground">
      {/* Toolbar — hidden when printing */}
      <div className="print-hidden flex items-center justify-between gap-3 py-4 border-b border-border mb-6">
        <Link
          href="/officer/reports"
          className="text-sm text-muted-foreground hover:text-foreground inline-flex items-center gap-1"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Reports
        </Link>
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 h-9 px-3 rounded-xl border border-primary/30 text-primary text-sm hover:bg-primary/5"
        >
          <Printer className="w-4 h-4" /> Print / Save as PDF
        </button>
      </div>

      {/* Printable masthead */}
      <header className="mb-6 pb-4 border-b border-foreground/20">
        <p className="text-xs uppercase tracking-wider text-muted-foreground">
          PARAYA · DYCI Center for Community Engagement
        </p>
        <h1 className="font-heading text-3xl font-bold mt-2 text-foreground">
          {report.title}
        </h1>
        <div className="mt-3 grid grid-cols-2 gap-x-8 gap-y-1 text-sm">
          <div>
            <span className="text-muted-foreground">Period:</span>{" "}
            <span className="text-foreground">{fmtDate(report.period_start)} – {fmtDate(report.period_end)}</span>
          </div>
          <div>
            <span className="text-muted-foreground">Status:</span>{" "}
            <span className="text-foreground capitalize">{report.status}</span>
          </div>
          <div>
            <span className="text-muted-foreground">Generated:</span>{" "}
            <span className="text-foreground">{fmtDate(report.created_at)}</span>
          </div>
          {generatedBy && (
            <div>
              <span className="text-muted-foreground">Generated by:</span>{" "}
              <span className="text-foreground">{generatedBy}</span>
            </div>
          )}
        </div>
      </header>

      {/* Narrative body — split on blank lines, each paragraph */}
      <main className="space-y-4 text-foreground leading-relaxed">
        {report.narrative.split("\n\n").map((para, i) => (
          <p key={i} className="text-base">{para}</p>
        ))}
      </main>

      {/* Disclaimer footer */}
      <footer className="mt-10 pt-4 border-t border-foreground/20 text-xs text-muted-foreground">
        AI-generated narrative. Reviewed and approved by PARAYA Office before official use.
      </footer>
    </div>
  );
}
