"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { DocumentManager } from "./DocumentManager";
import { Empty, Field, Panel, Phase2Notice, StatusPill, inputClass, jsonRequest, phase2Api, primaryButton, secondaryButton, textareaClass } from "./Phase2Ui";
import type { FinanceProposalDTO, ProgramFinanceDTO } from "@/lib/phase2/types";
import { FinanceIntegrityPanel } from "@/components/integrity/FinanceIntegrityPanel";

type FinanceQueueRow = { id: string; title: string; status: string; startsOn: string; endsOn: string; rowVersion: number; budgetRevisionId: string; budgetStatus: string; cashTotal: string; inKindTotal: string };
type ProgramQueueRow = { id: string; title: string; status: string; allocationStatus: string | null; allocationRevision: number | null; cashTotal: string; inKindTotal: string };

export function FinanceOperations({ canReviewProposal, canRecordActual, canReviewActual, canReviewLiquidation, canDocuments, canReviewDocuments, integrityEnabled, canIntegrityRead, canIntegrityRequest }: { canReviewProposal: boolean; canRecordActual: boolean; canReviewActual: boolean; canReviewLiquidation: boolean; canDocuments: boolean; canReviewDocuments: boolean; integrityEnabled: boolean; canIntegrityRead: boolean; canIntegrityRequest: boolean }) {
  const [proposals, setProposals] = useState<FinanceQueueRow[]>([]); const [programs, setPrograms] = useState<ProgramQueueRow[]>([]);
  const [proposalId, setProposalId] = useState(""); const [programId, setProgramId] = useState(""); const [proposal, setProposal] = useState<FinanceProposalDTO | null>(null); const [finance, setFinance] = useState<ProgramFinanceDTO | null>(null);
  const [message, setMessage] = useState<{ text: string; tone: "error" | "success" } | null>(null); const [busy, setBusy] = useState(false); const [remarks, setRemarks] = useState("");
  const load = useCallback(async () => {
    const [proposalResult, programResult] = await Promise.allSettled([
      canReviewProposal ? phase2Api<FinanceQueueRow[]>("/api/v2/finance/proposals") : Promise.resolve([]),
      phase2Api<ProgramQueueRow[]>("/api/v2/programs/finance"),
    ]);
    const proposalRows = proposalResult.status === "fulfilled" ? proposalResult.value : [];
    const programRows = programResult.status === "fulfilled" ? programResult.value : [];
    setProposals(proposalRows); setPrograms(programRows);
    setProposalId((current) => current || proposalRows[0]?.id || "");
    setProgramId((current) => current || programRows[0]?.id || "");
    if (programResult.status === "rejected") setMessage({ text: programResult.reason instanceof Error ? programResult.reason.message : "Unable to load program Finance queue", tone: "error" });
  }, [canReviewProposal]);
  const loadProposal = useCallback(async (id: string) => { if (!id) return setProposal(null); try { setProposal(await phase2Api(`/api/v2/finance/proposals/${id}`)); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load Finance proposal", tone: "error" }); } }, []);
  const loadFinance = useCallback(async (id: string) => { if (!id) return setFinance(null); try { setFinance(await phase2Api(`/api/v2/programs/${id}/finance`)); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load program finance", tone: "error" }); } }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void loadProposal(proposalId); }, [loadProposal, proposalId]); useEffect(() => { void loadFinance(programId); }, [loadFinance, programId]);
  async function mutate(task: () => Promise<unknown>, success: string) { setBusy(true); setMessage(null); try { await task(); setMessage({ text: success, tone: "success" }); await load(); if (proposalId) await loadProposal(proposalId); if (programId) await loadFinance(programId); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Operation failed", tone: "error" }); } finally { setBusy(false); } }
  async function proposalAction(action: "finance_return" | "finance_clear") { if (!proposal) return; await mutate(() => phase2Api(`/api/v2/proposals/${proposal.proposal.id}/workflow`, jsonRequest("POST", { action, expectedVersion: proposal.proposal.rowVersion, remarks: remarks || undefined, acknowledgedWarningCodes: proposal.proposal.requiredWarnings })), action === "finance_clear" ? "Finance clearance recorded against the frozen revision." : "Budget returned; the reviewed revision remains immutable."); setRemarks(""); }
  async function allocationAction(action: "submit" | "return" | "activate", revision: ProgramFinanceDTO["allocationRevisions"][number]) { if (!finance) return; await mutate(() => phase2Api(`/api/v2/programs/${finance.programId}/finance/allocations/${revision.id}`, jsonRequest("POST", { action, expectedVersion: revision.rowVersion, reason: remarks || undefined })), `Allocation ${action} recorded.`); setRemarks(""); }
  async function expenditure(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!finance) return; const form = new FormData(event.currentTarget); await mutate(() => phase2Api(`/api/v2/programs/${finance.programId}/finance/expenditures`, jsonRequest("POST", { budgetItemId: form.get("budgetItemId"), amount: form.get("amount"), spentOn: form.get("spentOn"), payeeLabel: form.get("payeeLabel") || null, description: form.get("description"), receiptDocumentId: null, receiptExceptionReason: form.get("receiptExceptionReason"), varianceExplanation: form.get("varianceExplanation") || null })), "Pending expenditure recorded for Finance review."); event.currentTarget.reset(); }
  async function reviewExpenditure(id: string, rowVersion: number, action: "verify" | "return") { if (!finance) return; await mutate(() => phase2Api(`/api/v2/programs/${finance.programId}/finance/expenditures/${id}/review`, jsonRequest("POST", { action, expectedVersion: rowVersion, reason: remarks })), `Expenditure ${action} recorded.`); setRemarks(""); }
  async function liquidation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!finance) return; const form = new FormData(event.currentTarget); const ids = finance.expenditures.filter((item) => item.status === "verified").map((item) => item.id); await mutate(() => phase2Api(`/api/v2/programs/${finance.programId}/finance/liquidations`, jsonRequest("POST", { summary: { periodStart: form.get("periodStart"), periodEnd: form.get("periodEnd"), narrative: form.get("narrative"), exceptionNotes: form.get("exceptionNotes") || null }, expenditureIds: ids })), "Liquidation draft created from unclaimed verified expenditures."); event.currentTarget.reset(); }
  async function liquidationAction(id: string, rowVersion: number, action: "submit" | "return" | "verify" | "void") { if (!finance) return; await mutate(() => phase2Api(`/api/v2/programs/${finance.programId}/finance/liquidations/${id}`, jsonRequest("POST", { action, expectedVersion: rowVersion, remarks: remarks || undefined })), `Liquidation ${action} recorded.`); setRemarks(""); }

  return <div className="space-y-5" data-testid="finance-operations">
    {message && <Phase2Notice message={message.text} tone={message.tone} />}
    {canReviewProposal && <Panel title="Proposal budget review queue" description="Finance can clear or return the exact frozen budget, but cannot edit figures."><select className={inputClass} value={proposalId} onChange={(event) => setProposalId(event.target.value)}><option value="">Select a proposal</option>{proposals.map((row) => <option key={row.id} value={row.id}>{row.title} — {row.budgetStatus}</option>)}</select>{proposal && <div className="mt-4 space-y-3"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Proposal status" value={<StatusPill value={proposal.proposal.status} />} /><Field label="Budget revision" value={proposal.budget.revisionNumber} /><Field label="Cash" value={`PHP ${proposal.budget.cashTotal}`} /><Field label="In kind" value={`PHP ${proposal.budget.inKindTotal}`} /><Field label="Funding cash" value={`PHP ${proposal.budget.fundingCashTotal}`} /><Field label="Reconciled" value={proposal.budget.reconciled ? "Yes" : "No"} /><Field label="Budget hash" value={proposal.budget.canonicalHash?.slice(0, 16) ?? "Not frozen"} /><Field label="Version" value={proposal.proposal.rowVersion} /></dl><div className="space-y-2">{proposal.budget.items?.map((item) => <div className="rounded border p-3 text-sm" key={item.id}>{item.description}<span className="float-right">{item.kind === "cash" ? "PHP" : "In kind"} {item.amount}</span></div>)}</div><textarea className={textareaClass} value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Finance review remarks" /><div className="flex gap-2"><button className={secondaryButton} disabled={busy || !remarks} onClick={() => void proposalAction("finance_return")}>Return immutable revision</button><button className={primaryButton} disabled={busy || !proposal.budget.reconciled} onClick={() => void proposalAction("finance_clear")}>Clear exact revision</button></div></div>}</Panel>}
    <Panel title="Program financial monitoring" description="Select an operational program; database identifiers are never typed manually."><select className={inputClass} value={programId} onChange={(event) => setProgramId(event.target.value)}><option value="">Select a program</option>{programs.map((row) => <option key={row.id} value={row.id}>{row.title} — {row.allocationStatus ?? "no allocation"}</option>)}</select>{programs.length === 0 && <Empty />}</Panel>
    {finance && <><Panel title={finance.title} description="Planned, pending, and verified amounts remain separate."><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Planned cash" value={`PHP ${finance.totals.plannedCash}`} /><Field label="Pending actual" value={`PHP ${finance.totals.pendingActual}`} /><Field label="Verified actual" value={`PHP ${finance.totals.verifiedActual}`} /><Field label="Remaining" value={`PHP ${finance.totals.remaining}`} /><Field label="Variance" value={`PHP ${finance.totals.variance}`} /><Field label="Planned in kind" value={`PHP ${finance.totals.plannedInKind}`} /></dl></Panel>
    <Panel title="Allocation revisions" description="Prepared revisions are reviewed without Finance editing their figures."><textarea className={textareaClass} value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Review or transition reason" />{finance.allocationRevisions.length === 0 ? <Empty /> : finance.allocationRevisions.map((revision) => <div className="mt-2 rounded border p-3 text-sm" key={revision.id}><div className="flex justify-between"><b>Revision {revision.revisionNumber}</b><StatusPill value={revision.status} /></div><div>Cash PHP {revision.cashTotal} · In kind PHP {revision.inKindTotal}</div><div className="mt-2 flex gap-2">{canRecordActual && ["draft", "returned"].includes(revision.status) && <button className={primaryButton} onClick={() => void allocationAction("submit", revision)}>Submit allocation</button>}{canReviewActual && revision.status === "submitted" && <><button className={secondaryButton} disabled={!remarks} onClick={() => void allocationAction("return", revision)}>Return</button><button className={primaryButton} onClick={() => void allocationAction("activate", revision)}>Activate</button></>}</div></div>)}</Panel>
    {canRecordActual && finance.allocation?.items && <Panel title="Record an actual" description="Cash evidence requires an approved receipt or a documented exception."><form onSubmit={expenditure} className="grid gap-3 md:grid-cols-3"><select className={inputClass} name="budgetItemId" required><option value="">Active allocation item</option>{finance.allocation.items.map((item) => <option key={item.id} value={item.id}>{item.description} — {item.kind}</option>)}</select><input className={inputClass} name="amount" inputMode="decimal" placeholder="Amount" required /><input className={inputClass} name="spentOn" type="date" required /><input className={inputClass} name="payeeLabel" placeholder="Payee label" /><input className={`${inputClass} md:col-span-2`} name="description" placeholder="Expenditure description" required /><input className={`${inputClass} md:col-span-2`} name="receiptExceptionReason" minLength={10} placeholder="Receipt exception reason (or upload an approved receipt first)" required /><input className={inputClass} name="varianceExplanation" placeholder="Variance explanation when overspending" /><button className={`${primaryButton} md:col-span-3`} disabled={busy}>Record pending actual</button></form></Panel>}
    <Panel title="Expenditures"><textarea className={textareaClass} value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Finance return reason" />{finance.expenditures.length === 0 ? <Empty /> : <div className="mt-3 space-y-2">{finance.expenditures.map((item) => <article className="rounded border p-3 text-sm" key={item.id}><div className="flex justify-between"><b>{item.description}</b><StatusPill value={item.status} /></div><div>{item.spentOn} · PHP {item.amount}</div>{canReviewActual && item.status === "pending" && <div className="mt-2 flex gap-2"><button className={secondaryButton} disabled={!remarks} onClick={() => void reviewExpenditure(item.id, item.rowVersion, "return")}>Return</button><button className={primaryButton} onClick={() => void reviewExpenditure(item.id, item.rowVersion, "verify")}>Verify</button></div>}</article>)}</div>}</Panel>
    <DocumentManager kind="program_finance" parentId={finance.programId} canUpload={canDocuments} canReview={canReviewDocuments} />
    <Panel title="Liquidation" description="Claims bind exact verified expenditures; overlapping active claims are rejected.">{canRecordActual && <form onSubmit={liquidation} className="grid gap-2 md:grid-cols-2"><input className={inputClass} name="periodStart" type="date" required /><input className={inputClass} name="periodEnd" type="date" required /><textarea className={`${textareaClass} md:col-span-2`} name="narrative" minLength={10} placeholder="Bounded liquidation narrative" required /><input className={`${inputClass} md:col-span-2`} name="exceptionNotes" placeholder="Exception notes" /><button className={`${primaryButton} md:col-span-2`} disabled={!finance.expenditures.some((item) => item.status === "verified")}>Create draft from verified actuals</button></form>}<div className="mt-3 space-y-2">{finance.liquidations.map((item) => <div className="rounded border p-3 text-sm" key={item.id}><div className="flex justify-between"><b>Liquidation {item.revisionNumber}</b><StatusPill value={item.status} /></div><div>PHP {item.totalSubmitted} · {item.expenditureIds.length} claimed expenditures</div><div className="mt-2 flex gap-2">{canRecordActual && ["draft", "returned"].includes(item.status) && <button className={primaryButton} onClick={() => void liquidationAction(item.id, item.rowVersion, "submit")}>Submit</button>}{canReviewLiquidation && item.status === "submitted" && <><button className={secondaryButton} disabled={!remarks} onClick={() => void liquidationAction(item.id, item.rowVersion, "return")}>Return</button><button className={primaryButton} disabled={!remarks} onClick={() => void liquidationAction(item.id, item.rowVersion, "verify")}>Verify</button></>}</div></div>)}</div></Panel></>}
    {canIntegrityRead && <FinanceIntegrityPanel enabled={integrityEnabled} canRead={canIntegrityRead} canRequest={canIntegrityRequest} budget={proposal?.budget ?? null} liquidations={finance?.liquidations ?? []} />}
  </div>;
}
