"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { DocumentManager } from "./DocumentManager";
import { Empty, Field, Panel, Phase2Notice, StatusPill, inputClass, jsonRequest, phase2Api, primaryButton, secondaryButton, textareaClass } from "./Phase2Ui";

type HistoricalRow = { id: string; code: string; title: string; summary: string | null; category: string; datePrecision: string; startsOn: string | null; endsOn: string | null; beneficiaryCount: number | null; volunteerCount: number | null; volunteerHours: string | null; budgetTotal: string | null; currency: string; sourceType: string; status: string; quality: string; rowVersion: number };
type HistoricalDetail = HistoricalRow & { resources: string | null; historicalNeedDescription: string | null; outcomes: string | null; followUp: string | null; sourceNotes: string | null; sdgs: Array<{ number: number; source: string }>; events: Array<{ id: string; action: string; fromStatus: string | null; toStatus: string | null; quality: string | null; remarks: string | null; occurredAt: string }> };
type HistoricalAnalytics = {
  scope?: "all" | "own_barangay";
  operational?: { recordCount?: number; budgetTotal?: string };
  verifiedHistorical?: { recordCount?: number; beneficiaryCount?: number; volunteerCount?: number; volunteerHours?: string; budgetTotal?: string };
  unverifiedHistorical?: { recordCount?: number; beneficiaryCount?: number; volunteerCount?: number; volunteerHours?: string; budgetTotal?: string };
};
type ImportBatch = { id: string; status: string; totalRows: number; validRows: number; errorRows: number; duplicateRows: number; rows?: Array<{ rowKey: string; errors: string[] }> };

export function HistoricalOperations({ canCreate, canImport, canReview, canDocuments, canReviewDocuments }: { canCreate: boolean; canImport: boolean; canReview: boolean; canDocuments: boolean; canReviewDocuments: boolean }) {
  const canDetail = canCreate || canImport || canReview;
  const [rows, setRows] = useState<HistoricalRow[]>([]); const [selectedId, setSelectedId] = useState(""); const [detail, setDetail] = useState<HistoricalDetail | null>(null);
  const [analytics, setAnalytics] = useState<HistoricalAnalytics | null>(null); const [batch, setBatch] = useState<ImportBatch | null>(null);
  const [message, setMessage] = useState<{ text: string; tone: "error" | "success" } | null>(null); const [busy, setBusy] = useState(false); const [remarks, setRemarks] = useState("");
  const load = useCallback(async () => { try { const metrics = await phase2Api<HistoricalAnalytics>("/api/v2/historical-programs/analytics"); const programs = canDetail ? await phase2Api<HistoricalRow[]>("/api/v2/historical-programs") : []; setRows(programs); setAnalytics(metrics); setSelectedId((current) => canDetail ? current || programs[0]?.id || "" : ""); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load historical programs", tone: "error" }); } }, [canDetail]);
  const loadDetail = useCallback(async (id: string) => { if (!id) return setDetail(null); try { setDetail(await phase2Api(`/api/v2/historical-programs/${id}`)); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load historical detail", tone: "error" }); } }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { if (canDetail) void loadDetail(selectedId); else setDetail(null); }, [canDetail, loadDetail, selectedId]);
  async function mutate(task: () => Promise<unknown>, success: string) { setBusy(true); setMessage(null); try { await task(); setMessage({ text: success, tone: "success" }); await load(); if (selectedId) await loadDetail(selectedId); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Operation failed", tone: "error" }); } finally { setBusy(false); } }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const precision = String(form.get("datePrecision")); await mutate(() => phase2Api("/api/v2/historical-programs", jsonRequest("POST", { title: form.get("title"), summary: form.get("summary") || null, category: form.get("category"), datePrecision: precision, startsOn: precision === "unknown" ? null : form.get("startsOn"), endsOn: form.get("endsOn") || null, beneficiaryCount: form.get("beneficiaryCount") ? Number(form.get("beneficiaryCount")) : null, volunteerCount: form.get("volunteerCount") ? Number(form.get("volunteerCount")) : null, volunteerHours: form.get("volunteerHours") || null, budgetTotal: form.get("budgetTotal") || null, currency: "PHP", resources: form.get("resources") || null, historicalNeedDescription: form.get("historicalNeedDescription") || null, outcomes: form.get("outcomes") || null, followUp: form.get("followUp") || null, sourceType: form.get("sourceType"), sourceNotes: form.get("sourceNotes") || null, partnerIds: [], barangayIds: [], needIds: [], sdgs: [] })), "Historical draft created."); event.currentTarget.reset(); }
  async function workflow(action: "submit" | "return" | "accept" | "archive", quality?: string) { if (!detail) return; await mutate(() => phase2Api(`/api/v2/historical-programs/${detail.id}/workflow`, jsonRequest("POST", { action, expectedVersion: detail.rowVersion, quality, remarks: remarks || undefined })), `Historical record ${action.replace("submit", "submitted")}.`); setRemarks(""); }
  async function preview(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { const staged = await phase2Api<ImportBatch>("/api/v2/historical-programs/imports/preview", { method: "POST", body: form }); setBatch(staged); setMessage({ text: "Import validated. Review errors and duplicate candidates before commit.", tone: "success" }); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Import validation failed", tone: "error" }); } finally { setBusy(false); } }
  async function commit() { if (!batch) return; await mutate(() => phase2Api(`/api/v2/historical-programs/imports/${batch.id}/commit`, { method: "POST" }), "Ready import committed as drafts."); setBatch(null); }

  return <div className="space-y-5" data-testid="historical-operations">
    {message && <Phase2Notice message={message.text} tone={message.tone} />}
    <div className="grid gap-4 sm:grid-cols-2"><Panel title="Verified historical metrics"><Field label="Reviewed records" value={analytics?.verifiedHistorical?.recordCount ?? 0} /><Field label="Aggregate beneficiaries" value={analytics?.verifiedHistorical?.beneficiaryCount ?? 0} /></Panel><Panel title="Unverified historical metrics"><Field label="Labeled records" value={analytics?.unverifiedHistorical?.recordCount ?? 0} /><Field label="Aggregate beneficiaries" value={analytics?.unverifiedHistorical?.beneficiaryCount ?? 0} /></Panel></div>
    {canCreate && <Panel title="Encode a historical program" description="Unknown dates stay draft and outside the five-year metric until eligibility is established."><form onSubmit={create} className="grid gap-3 md:grid-cols-3"><input className={inputClass} name="title" placeholder="Program title" required /><input className={inputClass} name="category" placeholder="Controlled category" required /><select className={inputClass} name="datePrecision"><option value="exact">Exact date</option><option value="month">Month/year</option><option value="year">Year only</option><option value="unknown">Unknown</option></select><input className={inputClass} name="startsOn" type="date" /><input className={inputClass} name="endsOn" type="date" /><select className={inputClass} name="sourceType"><option value="excel">Excel</option><option value="word">Word</option><option value="pdf">PDF</option><option value="paper">Paper</option><option value="database">Database</option><option value="other">Other</option></select><input className={inputClass} name="beneficiaryCount" type="number" min="0" placeholder="Aggregate beneficiaries" /><input className={inputClass} name="volunteerCount" type="number" min="0" placeholder="Aggregate volunteers" /><input className={inputClass} name="volunteerHours" inputMode="decimal" placeholder="Aggregate volunteer hours" /><input className={inputClass} name="budgetTotal" inputMode="decimal" placeholder="Historical PHP total" /><input className={`${inputClass} md:col-span-2`} name="sourceNotes" placeholder="Source provenance" /><textarea className={`${textareaClass} md:col-span-3`} name="summary" placeholder="Reviewed summary (no named beneficiaries or volunteers)" /><textarea className={textareaClass} name="resources" placeholder="Aggregate resources" /><textarea className={textareaClass} name="historicalNeedDescription" placeholder="Historical need" /><textarea className={textareaClass} name="outcomes" placeholder="Aggregate outcomes" /><textarea className={`${textareaClass} md:col-span-3`} name="followUp" placeholder="Follow-up" /><button className={`${primaryButton} md:col-span-3`} disabled={busy}>Save draft</button></form></Panel>}
    {canImport && <Panel title="Controlled spreadsheet intake" description="Use the versioned template. Raw workbook bytes are not retained."><div className="flex flex-wrap gap-2"><a className={secondaryButton} href="/api/v2/historical-programs/imports/template?format=xlsx">XLSX template</a><a className={secondaryButton} href="/api/v2/historical-programs/imports/template?format=programs_csv">Programs CSV</a></div><form onSubmit={preview} className="mt-3 flex flex-wrap gap-2"><input className={inputClass} name="workbook" type="file" accept=".xlsx,.csv" required /><button className={primaryButton} disabled={busy}>Validate replacement upload</button></form>{batch && <div className="mt-3 rounded-md border p-3 text-sm"><div className="flex flex-wrap gap-3"><StatusPill value={batch.status} /><span>{batch.validRows} valid</span><span>{batch.errorRows} errors</span><span>{batch.duplicateRows} duplicates</span></div>{batch.rows?.filter((row) => row.errors.length).map((row) => <div className="mt-2 rounded bg-red-50 p-2" key={row.rowKey}><b>{row.rowKey}</b>: {row.errors.join("; ")}</div>)}<button className={`${primaryButton} mt-3`} disabled={batch.status !== "ready"} onClick={() => void commit()}>Commit ready batch</button></div>}</Panel>}
    {canDetail && <Panel title="Historical review queue"><select data-testid="historical-selector" className={inputClass} value={selectedId} onChange={(event) => setSelectedId(event.target.value)}><option value="">Select a record</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.code} — {row.title} ({row.status})</option>)}</select>{rows.length === 0 && <Empty />}</Panel>}
    {detail && <><Panel title={detail.title} description={`${detail.code} · ${detail.category}`} actions={<><StatusPill value={detail.status} /> <StatusPill value={detail.quality} /></>}><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Date precision" value={detail.datePrecision} /><Field label="Date" value={detail.startsOn ?? "Unknown"} /><Field label="Beneficiaries" value={detail.beneficiaryCount ?? "Not recorded"} /><Field label="Volunteers" value={detail.volunteerCount ?? "Not recorded"} /><Field label="Volunteer hours" value={detail.volunteerHours} /><Field label="Historical budget" value={detail.budgetTotal ? `PHP ${detail.budgetTotal}` : "Not recorded"} /><Field label="Source" value={detail.sourceType} /><Field label="Version" value={detail.rowVersion} /></dl><p className="rounded-md bg-slate-50 p-3 text-sm">{detail.summary ?? "No summary recorded."}</p>{canReview && <div className="space-y-2 rounded-md border p-3"><textarea className={textareaClass} value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Review remarks" /><div className="flex flex-wrap gap-2">{["draft", "returned"].includes(detail.status) && <button className={primaryButton} onClick={() => void workflow("submit")}>Submit for review</button>}{detail.status === "pending_review" && <><button className={secondaryButton} disabled={remarks.length < 1} onClick={() => void workflow("return")}>Return</button><button className={primaryButton} disabled={remarks.length < 1} onClick={() => void workflow("accept", "partial_verified")}>Accept as appropriately labeled</button></>}{detail.status === "accepted" && <button className={secondaryButton} disabled={remarks.length < 1} onClick={() => void workflow("archive")}>Archive</button>}</div></div>}</Panel><DocumentManager kind="historical" parentId={detail.id} canUpload={canDocuments && ["draft", "returned"].includes(detail.status)} canReview={canReviewDocuments} /><Panel title="Immutable review timeline">{detail.events.length === 0 ? <Empty /> : <ol className="space-y-2">{detail.events.map((event) => <li key={event.id} className="rounded-md border p-3 text-sm"><b>{event.action.replaceAll("_", " ")}</b> · {event.fromStatus ?? "new"} → {event.toStatus ?? "same"}<div className="text-xs text-slate-500">{new Date(event.occurredAt).toLocaleString()}</div>{event.remarks && <p>{event.remarks}</p>}</li>)}</ol>}</Panel></>}
  </div>;
}
