"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { DocumentManager } from "./DocumentManager";
import { Empty, Field, Panel, Phase2Notice, StatusPill, inputClass, jsonRequest, phase2Api, primaryButton } from "./Phase2Ui";

type Partner = { id: string; code: string; name: string; type: string; classification: string; lifecycle: string; rowVersion: number; roles: string[]; currentTerm: { status: string; derivedStatus: string; startsOn: string; expiresOn: string | null } | null };
type Contact = { id: string; fullName: string; title: string | null; email: string | null; phone: string | null; preferredChannel: string; isPrimary: boolean; statusEmailOptIn: boolean; activeFrom: string; activeUntil: string | null; rowVersion: number };
type Term = { id: string; status: string; derivedStatus: string; startsOn: string; expiresOn: string | null; responsibleOfficerId: string; rowVersion: number };
type Detail = Partner & { legalName: string | null; contacts: Contact[]; terms: Term[]; metrics: { programCount: number; proposalCount: number; historicalVerifiedCount: number; remainingNeedCount: number }; timeline: Array<{ id: string; type: string; reason: string | null; occurredAt: string }>; needs: Array<{ id: string; category: string; coverage: string; notes: string | null }> };
type Catalog = { entityTypes: string[]; officers: Array<{ id: string; name: string; role: string }>; barangays: Array<{ id: string; name: string }>; policies: Array<{ entityType: string; agreementRequired: boolean; effectiveFrom: string }> };
type Mapping = { legacyUserId: string; legacyEmail: string; legacyRole: string; organizationName: string | null; partnerId: string | null; partnerName: string | null; reconciliationStatus: string; responsibleOfficerId: string | null; proposalCount: number; programCount: number; pendingWorkCount: number; rowVersion: number; authSuspensionStatus: string };

export function PartnerOperations({ canManage, canContacts, canRenew, canMap, canDocuments, canReviewDocuments }: { canManage: boolean; canContacts: boolean; canRenew: boolean; canMap: boolean; canDocuments: boolean; canReviewDocuments: boolean }) {
  const [partners, setPartners] = useState<Partner[]>([]); const [selectedId, setSelectedId] = useState(""); const [detail, setDetail] = useState<Detail | null>(null);
  const [catalog, setCatalog] = useState<Catalog | null>(null); const [mappings, setMappings] = useState<Mapping[]>([]);
  const [message, setMessage] = useState<{ text: string; tone: "error" | "success" } | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    try {
      const [partnerRows, catalogData, mappingRows] = await Promise.all([
        phase2Api<Partner[]>("/api/v2/partners"),
        canManage ? phase2Api<Catalog>("/api/v2/partners/catalog") : Promise.resolve(null),
        canMap ? phase2Api<Mapping[]>("/api/v2/legacy-partner-mappings") : Promise.resolve([]),
      ]);
      setPartners(partnerRows); setCatalog(catalogData); setMappings(mappingRows); setSelectedId((current) => current || partnerRows[0]?.id || "");
    } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load Partner operations", tone: "error" }); }
  }, [canManage, canMap]);
  const loadDetail = useCallback(async (id: string) => { if (!id) return setDetail(null); try { setDetail(await phase2Api(`/api/v2/partners/${id}`)); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Unable to load Partner", tone: "error" }); } }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { void loadDetail(selectedId); }, [loadDetail, selectedId]);
  const activeTerm = useMemo(() => detail?.terms.find((term) => term.status === "active") ?? detail?.terms[0] ?? null, [detail]);

  async function mutate(task: () => Promise<unknown>, success: string) { setBusy(true); setMessage(null); try { await task(); setMessage({ text: success, tone: "success" }); await load(); if (selectedId) await loadDetail(selectedId); } catch (error) { setMessage({ text: error instanceof Error ? error.message : "Operation failed", tone: "error" }); } finally { setBusy(false); } }
  async function createPartner(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const roles = ["partner", "proponent"].filter((role) => form.get(role) === "on"); await mutate(() => phase2Api("/api/v2/partners", jsonRequest("POST", { name: form.get("name"), legalName: form.get("legalName") || null, type: form.get("type"), classification: form.get("classification"), barangayId: form.get("barangayId") || null, roles })), "Partner entity created."); event.currentTarget.reset(); }
  async function addContact(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const form = new FormData(event.currentTarget); const optedIn = form.get("statusEmailOptIn") === "on"; await mutate(() => phase2Api(`/api/v2/partners/${detail.id}/contacts`, jsonRequest("POST", { fullName: form.get("fullName"), title: form.get("title") || null, email: form.get("email") || null, phone: form.get("phone") || null, preferredChannel: form.get("preferredChannel"), isPrimary: form.get("isPrimary") === "on", statusEmailOptIn: optedIn, consentSource: optedIn ? form.get("consentSource") : null, consentAt: optedIn ? new Date().toISOString() : null, activeFrom: form.get("activeFrom"), activeUntil: null })), "Contact added."); event.currentTarget.reset(); }
  async function renew(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail || !activeTerm) return; const form = new FormData(event.currentTarget); await mutate(() => phase2Api(`/api/v2/partners/${detail.id}/terms/renew`, jsonRequest("POST", { expectedVersion: activeTerm.rowVersion, startsOn: form.get("startsOn"), expiresOn: form.get("expiresOn") || null, responsibleOfficerId: form.get("officerId"), agreementDocumentId: null, agreementExceptionReason: form.get("exceptionReason") || null, agreementExceptionDueOn: form.get("exceptionDueOn") || null })), "Relationship renewed and predecessor closed."); event.currentTarget.reset(); }
  async function reconcile(event: FormEvent<HTMLFormElement>, mapping: Mapping) { event.preventDefault(); const form = new FormData(event.currentTarget); await mutate(() => phase2Api(`/api/v2/legacy-partner-mappings/${mapping.legacyUserId}`, jsonRequest("POST", { partnerId: form.get("partnerId"), responsibleOfficerId: form.get("officerId"), expectedVersion: mapping.rowVersion, action: form.get("action"), notes: form.get("notes") })), "Legacy mapping action recorded."); }

  return <div className="space-y-5" data-testid="partner-operations">
    {message && <Phase2Notice message={message.text} tone={message.tone} />}
    {canManage && catalog && <Panel title="Register a Partner or Proponent" description="Organizations remain non-login records. Barangays continue to use the geographic source of truth."><form onSubmit={createPartner} className="grid gap-3 md:grid-cols-3"><input className={inputClass} name="name" placeholder="Display name" required /><input className={inputClass} name="legalName" placeholder="Legal name (optional)" /><select className={inputClass} name="type">{catalog.entityTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select><select className={inputClass} name="classification"><option value="internal">Internal DYCI</option><option value="external">External</option></select><select className={inputClass} name="barangayId"><option value="">Not linked to a barangay</option>{catalog.barangays.map((barangay) => <option key={barangay.id} value={barangay.id}>{barangay.name}</option>)}</select><div className="flex items-center gap-4 text-sm"><label><input type="checkbox" name="partner" defaultChecked /> Partner</label><label><input type="checkbox" name="proponent" /> Proponent</label></div><button disabled={busy} className={`${primaryButton} md:col-span-3`}>Create non-login entity</button></form></Panel>}
    <Panel title="Partner registry" description="Filter and open records without entering database identifiers."><select data-testid="partner-selector" className={inputClass} value={selectedId} onChange={(event) => setSelectedId(event.target.value)}><option value="">Select a Partner</option>{partners.map((partner) => <option key={partner.id} value={partner.id}>{partner.code} — {partner.name}</option>)}</select>{partners.length === 0 && <Empty />}</Panel>
    {detail && <><Panel title={detail.name} description={`${detail.code} · ${detail.type.replaceAll("_", " ")}`} actions={<StatusPill value={detail.lifecycle} />} testId="partner-detail"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Classification" value={detail.classification} /><Field label="Roles" value={detail.roles.join(", ")} /><Field label="Programs" value={detail.metrics.programCount} /><Field label="Proposals" value={detail.metrics.proposalCount} /><Field label="Verified history" value={detail.metrics.historicalVerifiedCount} /><Field label="Remaining needs" value={detail.metrics.remainingNeedCount} /><Field label="Relationship" value={<StatusPill value={activeTerm?.derivedStatus} />} /><Field label="Version" value={detail.rowVersion} /></dl></Panel>
    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Contacts" description="Only opted-in active contacts can receive status email.">{detail.contacts.length === 0 ? <Empty /> : <div className="space-y-2">{detail.contacts.map((contact) => <div className="rounded-md border p-3 text-sm" key={contact.id}><div className="flex justify-between"><b>{contact.fullName}</b>{contact.isPrimary && <StatusPill value="primary" />}</div><div className="mt-1 text-slate-600">{contact.title ?? "No title"} · {contact.preferredChannel} · email {contact.statusEmailOptIn ? "opted in" : "suppressed"}</div></div>)}</div>}{canContacts && <form onSubmit={addContact} className="mt-4 grid gap-2 sm:grid-cols-2"><input className={inputClass} name="fullName" placeholder="Contact name" required /><input className={inputClass} name="title" placeholder="Title" /><input className={inputClass} name="email" type="email" placeholder="Email" /><input className={inputClass} name="phone" placeholder="Phone" /><select className={inputClass} name="preferredChannel"><option value="email">Email</option><option value="phone">Phone</option><option value="sms">SMS</option><option value="manual">Manual</option></select><input className={inputClass} name="activeFrom" type="date" required /><label className="text-sm"><input name="isPrimary" type="checkbox" /> Active primary contact</label><label className="text-sm"><input name="statusEmailOptIn" type="checkbox" /> Status-email opt-in</label><input className={`${inputClass} sm:col-span-2`} name="consentSource" placeholder="Opt-in consent source (required when opted in)" /><button className={`${primaryButton} sm:col-span-2`} disabled={busy}>Add contact</button></form>}</Panel>
    <Panel title="Relationship terms" description="Expiry status is derived from dates; renewal always creates a successor.">{detail.terms.map((term) => <div className="mb-2 rounded-md border p-3 text-sm" key={term.id}><div className="flex justify-between"><span>{term.startsOn} to {term.expiresOn ?? "open-ended"}</span><StatusPill value={term.derivedStatus} /></div></div>)}{canRenew && activeTerm && catalog && <form onSubmit={renew} className="mt-4 grid gap-2 sm:grid-cols-2"><input className={inputClass} name="startsOn" type="date" required /><input className={inputClass} name="expiresOn" type="date" /><select className={`${inputClass} sm:col-span-2`} name="officerId" required><option value="">Responsible PARAYA officer</option>{catalog.officers.map((officer) => <option key={officer.id} value={officer.id}>{officer.name} — {officer.role}</option>)}</select><input className={inputClass} name="exceptionReason" placeholder="Director agreement exception" /><input className={inputClass} name="exceptionDueOn" type="date" /><button className={`${primaryButton} sm:col-span-2`} disabled={busy}>Renew relationship</button></form>}</Panel></div>
    <DocumentManager kind="partnership" parentId={detail.id} canUpload={canDocuments} canReview={canReviewDocuments} />
    <Panel title="Needs and timeline"><div className="grid gap-4 lg:grid-cols-2"><div>{detail.needs?.length ? detail.needs.map((need) => <div className="mb-2 rounded border p-3 text-sm" key={need.id}>{need.category} · <StatusPill value={need.coverage} /><p className="mt-1 text-slate-600">{need.notes}</p></div>) : <Empty>No linked needs.</Empty>}</div><ol className="space-y-2">{detail.timeline.map((event) => <li className="rounded border-l-4 p-3 text-sm" key={event.id}><b>{event.type.replaceAll("_", " ")}</b><div className="text-xs text-slate-500">{new Date(event.occurredAt).toLocaleString()}</div>{event.reason && <p>{event.reason}</p>}</li>)}</ol></div></Panel></>}
    {canMap && catalog && <Panel title="Legacy institutional-account reconciliation" description="Historical authorship is preserved; real Auth suspension remains a separately authorized production action.">{mappings.length === 0 ? <Empty>No candidate mappings.</Empty> : <div className="space-y-3">{mappings.map((mapping) => <form onSubmit={(event) => void reconcile(event, mapping)} key={mapping.legacyUserId} className="grid gap-2 rounded-md border p-4 md:grid-cols-4"><div className="md:col-span-4"><b>{mapping.organizationName ?? mapping.legacyEmail}</b><span className="ml-2"><StatusPill value={mapping.reconciliationStatus} /></span><p className="text-xs text-slate-500">{mapping.legacyRole} · {mapping.proposalCount} proposals · {mapping.programCount} programs · {mapping.pendingWorkCount} pending</p></div><select className={inputClass} name="partnerId" defaultValue={mapping.partnerId ?? ""} required><option value="">Mapped Partner</option>{partners.map((partner) => <option key={partner.id} value={partner.id}>{partner.name}</option>)}</select><select className={inputClass} name="officerId" defaultValue={mapping.responsibleOfficerId ?? ""} required><option value="">Responsible officer</option>{catalog.officers.map((officer) => <option key={officer.id} value={officer.id}>{officer.name}</option>)}</select><select className={inputClass} name="action"><option value="start_review">Start review</option><option value="approve">Approve reconciliation</option><option value="sign_off">Sign off</option></select><input className={inputClass} name="notes" placeholder="Reconciliation notes" required minLength={5} /><button className={`${primaryButton} md:col-span-4`} disabled={busy}>Record mapping action</button></form>)}</div>}</Panel>}
  </div>;
}
