import { createAdminClient } from "@/lib/supabase/admin";
import { notFound } from "next/navigation";
import PpfClient from "./PpfClient";
import { authorizeCapability } from "@/lib/auth/authorize";
import { z } from "zod";

// Project Participation Form (PPF) print view.
// Server-fetches an allowlisted proposal/evidence projection and renders a
// printable form whose final approving authority is the PARAYA Director.
//
// The framework calls out an "auto-generated Project Participation Form PDF"
// as part of Sprint 6 — this is that, generated by the browser print dialog
// against the global print stylesheet (no PDF library required).

type Ctx = { params: Promise<{ id: string }> };
const proposalIdSchema = z.string().uuid();
const sourceTypeSchema = z.enum([
  "community_need", "survey", "survey_response", "field_observation",
  "household_profile", "profiling_evidence_snapshot",
]);
const provenanceSchema = z.enum(["validation", "advisory_planning"]);

export default async function PpfPage({ params }: Ctx) {
  const { id } = await params;
  if (!proposalIdSchema.safeParse(id).success) notFound();

  const access = await authorizeCapability("proposal.review");
  if (!access.ok) notFound();

  const admin = createAdminClient();
  const [proposalResult, linkResult, validationResult] = await Promise.all([
    admin
      .from("project_proposals")
      .select(`
        id, title, rationale, objectives, target_beneficiaries, expected_output,
        timeline_start, timeline_end, budget, status, created_at,
        community_validated_at,
        barangays(name),
        proposal_sdg_alignment(sdg_number, indicator),
        users:created_by(full_name)
      `)
      .eq("id", id)
      .maybeSingle(),
    // Validation linkage: cited community-engagement records.
    admin
      .from("proposal_validation_links")
      .select("id, source_type, source_id, provenance_kind, rationale")
      .eq("proposal_id", id)
      .order("created_at", { ascending: true }),
    // Validation events: any supplementary uploaded-evidence consultations.
    admin
      .from("proposal_validations")
      .select(`
        id, method, date_conducted, summary,
        proposal_validation_stakeholders(role, present),
        proposal_validation_evidence(id)
      `)
      .eq("proposal_id", id)
      .order("date_conducted", { ascending: true }),
  ]);

  if (proposalResult.error || linkResult.error || validationResult.error || !proposalResult.data) notFound();
  const proposal = proposalResult.data;
  const links = linkResult.data ?? [];
  const validations = validationResult.data ?? [];

  // ── Hydrate validation links with referenced record details ────────────
  type LinkRow = { id: string; source_type: string; source_id: string; provenance_kind: string; rationale: string };
  const linkRows = (links ?? []) as LinkRow[];
  const idsByType: Record<string, string[]> = {};
  for (const l of linkRows) {
    if (!sourceTypeSchema.safeParse(l.source_type).success
      || !provenanceSchema.safeParse(l.provenance_kind).success
      || !proposalIdSchema.safeParse(l.source_id).success) notFound();
    (idsByType[l.source_type] ??= []).push(l.source_id);
  }

  const [needsRes, surveysRes, responsesRes, obsRes, hpRes, evidenceRes] = await Promise.all([
    idsByType.community_need?.length
      ? admin.from("community_needs")
          .select("id, title, category, sitio, approval_status, barangays(name)")
          .in("id", idsByType.community_need)
      : Promise.resolve({ data: [] as Record<string, unknown>[], error: null }),
    idsByType.survey?.length
      ? admin.from("surveys")
          .select("id, title, status, barangays(name)")
          .in("id", idsByType.survey)
      : Promise.resolve({ data: [] as Record<string, unknown>[], error: null }),
    idsByType.survey_response?.length
      ? admin.from("survey_responses")
          .select("id, surveys(title)")
          .in("id", idsByType.survey_response)
      : Promise.resolve({ data: [] as Record<string, unknown>[], error: null }),
    idsByType.field_observation?.length
      ? admin.from("field_observations")
          .select("id, observation, observation_date, category, sitio, barangays(name)")
          .in("id", idsByType.field_observation)
      : Promise.resolve({ data: [] as Record<string, unknown>[], error: null }),
    idsByType.household_profile?.length
      ? admin.from("household_profiles")
          .select("id, household_number, sitio, barangays(name)")
          .in("id", idsByType.household_profile)
      : Promise.resolve({ data: [] as Record<string, unknown>[], error: null }),
    idsByType.profiling_evidence_snapshot?.length
      ? admin.from("profiling_evidence_snapshots").select("id, aggregate_schema_version, generated_at, content_hash, profiling_cycles(name, barangays(name))").in("id", idsByType.profiling_evidence_snapshot)
      : Promise.resolve({ data: [] as Record<string, unknown>[], error: null }),
  ]);

  if ([needsRes, surveysRes, responsesRes, obsRes, hpRes, evidenceRes].some((result) => result.error)) notFound();

  const detailIndex = new Map<string, Record<string, unknown>>();
  for (const row of (needsRes.data ?? []) as { id: string }[])    detailIndex.set(`community_need:${row.id}`,    row as unknown as Record<string, unknown>);
  for (const row of (surveysRes.data ?? []) as { id: string }[])  detailIndex.set(`survey:${row.id}`,            row as unknown as Record<string, unknown>);
  for (const row of (responsesRes.data ?? []) as { id: string }[]) detailIndex.set(`survey_response:${row.id}`, row as unknown as Record<string, unknown>);
  for (const row of (obsRes.data ?? []) as { id: string }[])      detailIndex.set(`field_observation:${row.id}`, row as unknown as Record<string, unknown>);
  for (const row of (hpRes.data ?? []) as { id: string }[])       detailIndex.set(`household_profile:${row.id}`, row as unknown as Record<string, unknown>);
  for (const row of (evidenceRes.data ?? []) as { id: string }[]) detailIndex.set(`profiling_evidence_snapshot:${row.id}`, row as unknown as Record<string, unknown>);

  const enrichedLinks = linkRows.map((l) => {
    const source = detailIndex.get(`${l.source_type}:${l.source_id}`);
    if (!source) notFound();
    const { id: _sourceId, ...details } = source;
    void _sourceId;
    return {
      id: l.id,
      source_type: l.source_type,
      provenance_kind: l.provenance_kind as "validation" | "advisory_planning",
      rationale: l.rationale,
      details,
    };
  });

  // ── Shape validation events for the printable form ─────────────────────
  type EventRow = {
    id: string; method: string; date_conducted: string; summary: string;
    proposal_validation_stakeholders: { role: string | null; present: boolean }[] | null;
    proposal_validation_evidence:     { id: string }[] | null;
  };
  const eventRows = (validations ?? []) as EventRow[];
  const enrichedEvents = eventRows.map((e) => ({
    id:             e.id,
    method:         e.method,
    date_conducted: e.date_conducted,
    summary:        e.summary,
    stakeholders:   e.proposal_validation_stakeholders ?? [],
    evidence_count: e.proposal_validation_evidence?.length ?? 0,
  }));

  const { error: auditError } = await admin.from("audit_logs").insert({
    user_id: access.actor.id,
    user_email: access.actor.email,
    action: "proposal.ppf.read",
    resource_type: "project_proposal",
    resource_id: id,
    level: "info",
    metadata: { validation_link_count: enrichedLinks.length, validation_event_count: enrichedEvents.length },
  });
  if (auditError) notFound();

  // Supabase returns embeds as arrays of one row. Normalize to the single-object
  // shape PpfClient expects.
  type ShapeFromDb = typeof proposal & {
    barangays: { name: string }[] | { name: string } | null;
    users:     { full_name: string | null }[] | { full_name: string | null } | null;
  };
  const raw = proposal as unknown as ShapeFromDb;
  const flatten = <T,>(v: T | T[] | null): T | null => Array.isArray(v) ? (v[0] ?? null) : v;

  return (
    <PpfClient
      proposal={{
        ...proposal,
        barangays: flatten(raw.barangays),
        users:     flatten(raw.users),
        // proposal_sdg_alignment is already an array, leave it
      }}
      validationLinks={enrichedLinks}
      validationEvents={enrichedEvents}
    />
  );
}
