import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { notFound } from "next/navigation";
import PpfClient from "./PpfClient";
import { authorizeCapability } from "@/lib/auth/authorize";

// Project Participation Form (PPF) print view.
// Server-fetches the proposal + its sign-up roster + sdg alignment + barangay,
// then renders a printable form that the Director / President can sign.
//
// The framework calls out an "auto-generated Project Participation Form PDF"
// as part of Sprint 6 — this is that, generated by the browser print dialog
// against the global print stylesheet (no PDF library required).

type Ctx = { params: Promise<{ id: string }> };

export default async function PpfPage({ params }: Ctx) {
  const { id } = await params;

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) notFound();

  const access = await authorizeCapability("proposal.read");
  if (!access.ok) notFound();

  const admin = createAdminClient();
  const [
    { data: proposal },
    { data: signups },
    { data: links },
    { data: validations },
  ] = await Promise.all([
    supabase
      .from("project_proposals")
      .select(`
        id, title, rationale, objectives, target_beneficiaries, expected_output,
        timeline_start, timeline_end, budget, status, created_at,
        community_validation_notes, community_validated_at,
        barangays(name, contact_person),
        proposal_sdg_alignment(sdg_number, indicator),
        users:created_by(full_name)
      `)
      .eq("id", id)
      .single(),
    // Roster placeholder — see note below.
    Promise.resolve({ data: [] as Array<{ full_name: string; email: string; role: string }> }),
    // Validation linkage: cited community-engagement records.
    admin
      .from("proposal_validation_links")
      .select("id, source_type, source_id, rationale, created_at")
      .eq("proposal_id", id)
      .order("created_at", { ascending: true }),
    // Validation events: any supplementary uploaded-evidence consultations.
    admin
      .from("proposal_validations")
      .select(`
        id, method, date_conducted, summary, created_at,
        proposal_validation_stakeholders(stakeholder_name, role, present),
        proposal_validation_evidence(id, file_name)
      `)
      .eq("proposal_id", id)
      .order("date_conducted", { ascending: true }),
  ]);

  if (!proposal) notFound();

  void signups;

  // ── Hydrate validation links with referenced record details ────────────
  type LinkRow = { id: string; source_type: string; source_id: string; rationale: string; created_at: string };
  const linkRows = (links ?? []) as LinkRow[];
  const idsByType: Record<string, string[]> = {};
  for (const l of linkRows) {
    (idsByType[l.source_type] ??= []).push(l.source_id);
  }

  const [needsRes, surveysRes, obsRes, hpRes, evidenceRes] = await Promise.all([
    idsByType.community_need?.length
      ? admin.from("community_needs")
          .select("id, title, category, sitio, approval_status, barangays(name)")
          .in("id", idsByType.community_need)
      : Promise.resolve({ data: [] as Record<string, unknown>[] }),
    idsByType.survey?.length
      ? admin.from("surveys")
          .select("id, title, status, barangays(name)")
          .in("id", idsByType.survey)
      : Promise.resolve({ data: [] as Record<string, unknown>[] }),
    idsByType.field_observation?.length
      ? admin.from("field_observations")
          .select("id, observation, observation_date, category, sitio, barangays(name)")
          .in("id", idsByType.field_observation)
      : Promise.resolve({ data: [] as Record<string, unknown>[] }),
    idsByType.household_profile?.length
      ? admin.from("household_profiles")
          .select("id, household_number, sitio, barangays(name)")
          .in("id", idsByType.household_profile)
      : Promise.resolve({ data: [] as Record<string, unknown>[] }),
    idsByType.profiling_evidence_snapshot?.length
      ? admin.from("profiling_evidence_snapshots").select("id, aggregate_schema_version, generated_at, content_hash, profiling_cycles(name, barangays(name))").in("id", idsByType.profiling_evidence_snapshot)
      : Promise.resolve({ data: [] as Record<string, unknown>[] }),
  ]);

  const detailIndex = new Map<string, Record<string, unknown>>();
  for (const row of (needsRes.data ?? []) as { id: string }[])    detailIndex.set(`community_need:${row.id}`,    row as unknown as Record<string, unknown>);
  for (const row of (surveysRes.data ?? []) as { id: string }[])  detailIndex.set(`survey:${row.id}`,            row as unknown as Record<string, unknown>);
  for (const row of (obsRes.data ?? []) as { id: string }[])      detailIndex.set(`field_observation:${row.id}`, row as unknown as Record<string, unknown>);
  for (const row of (hpRes.data ?? []) as { id: string }[])       detailIndex.set(`household_profile:${row.id}`, row as unknown as Record<string, unknown>);
  for (const row of (evidenceRes.data ?? []) as { id: string }[]) detailIndex.set(`profiling_evidence_snapshot:${row.id}`, row as unknown as Record<string, unknown>);

  const enrichedLinks = linkRows.map((l) => ({
    id:          l.id,
    source_type: l.source_type,
    source_id:   l.source_id,
    rationale:   l.rationale,
    created_at:  l.created_at,
    details:     detailIndex.get(`${l.source_type}:${l.source_id}`) ?? null,
  }));

  // ── Shape validation events for the printable form ─────────────────────
  type EventRow = {
    id: string; method: string; date_conducted: string; summary: string; created_at: string;
    proposal_validation_stakeholders: { stakeholder_name: string; role: string | null; present: boolean }[] | null;
    proposal_validation_evidence:     { id: string; file_name: string }[] | null;
  };
  const eventRows = (validations ?? []) as EventRow[];
  const enrichedEvents = eventRows.map((e) => ({
    id:             e.id,
    method:         e.method,
    date_conducted: e.date_conducted,
    summary:        e.summary,
    stakeholders:   e.proposal_validation_stakeholders ?? [],
    evidence_count: e.proposal_validation_evidence?.length ?? 0,
    evidence_names: (e.proposal_validation_evidence ?? []).map((f) => f.file_name),
  }));

  // Supabase returns embeds as arrays of one row. Normalize to the single-object
  // shape PpfClient expects.
  type ShapeFromDb = typeof proposal & {
    barangays: { name: string; contact_person?: string | null }[] | { name: string; contact_person?: string | null } | null;
    users:     { full_name: string | null }[] | { full_name: string | null } | null;
  };
  const raw = proposal as unknown as ShapeFromDb;
  const flatten = <T,>(v: T | T[] | null): T | null => Array.isArray(v) ? (v[0] ?? null) : v;

  return (
    <PpfClient
      proposal={{
        ...proposal,
        barangays: flatten(raw.barangays),
        users:     flatten(raw.users),
        // proposal_sdg_alignment is already an array, leave it
      }}
      validationLinks={enrichedLinks}
      validationEvents={enrichedEvents}
    />
  );
}
